### ISSUE TITLE
Unable to install from PyPI

### ISSUE THREAD

**Issue by jaraco** [hexdump42/isapi-wsgi#16]
Today I tried installing `isapi_wsgi>0.4` using pip and easy_install, but both techniques failed to locate any downloadable versions, probably because externally hosted packages have been deprecated in a lot of ways. Easiest solution - just upload packages to PyPI.

**Comment by hexdump42** [comment]
Have uploaded 0.4.2 source and installer files to pypi and removed google
code download url from pypi entry.

Unable to test as I am travelling but will do in the next couple of days.
